### ISSUE TITLE
Music MiniPlayer not working in macOS Sonoma Beta 7

### ISSUE THREAD

**Issue by LesleyGrossman** [marioaguzman/Music-Widget-MiniPlayer-Localization#2]
Hey Mr. Guzman, 

I don't know if it's appropriate to post this issue here, but since macOS Sonoma Beta 6 or 7 (7 for sure) the Music MiniPlayer application crashes as soon as a Music file is played. When the Music app is open without playback, it doesn't crash, but as soon as you hit the play button on any song the dialogue box appears that it quit unexpectedly. 
This is the case on both Apple Silicon and Intel Macs. 

If you would like I can also post the crash report here. 

Any fix would be much appreciated. 

Cheers!

**Comment by JohJakob** [comment]
@LesleyGrossman Mario has published updates for all his Music companion apps adding support for macOS 14 Sonoma. Can you please test if you still experience crashes with the latest update?

**Comment by LesleyGrossman** [comment]
> @LesleyGrossman Mario has published updates for all his Music companion apps adding support for macOS 14 Sonoma. Can you please test if you still experience crashes with the latest update?

Hi there, thank you for replying. Yes, installing the update made it work again. Cheers!

**Comment by jPress05** [comment]
I am still having problems on Sonoma and I have also tried to download it directly from the website (MBP 14" M1 Pro 2021). Loved the app when it worked though!

**Comment by JohJakob** [comment]
@jPress05 What is the issue that you encountered?
